---
- name: install dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - epel-release
  - glibc

- name: install nginx # Поскольку нужен epel-repo - нужно обновить его ссылки, поэтому дважды yum
  yum:
    name: "{{ item }}"
    state: present
  loop:
  - nginx

### RELOAD DAEMONS ###
- name: reload daemons
  systemd:
    daemon_reload: yes

### START SERVICES ###
- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: stop firewalld service
  systemd:
    name: firewalld
    state: stopped
    enabled: no