---
- name: stop services
  systemd:
    name: "{{ item }}"
    state: stopped
  ignore_errors: true
  loop: "{{ exporter_services }}"

- name: create dirs
  file:
    path: "{{ exporter_path }}"
    state: directory
    mode: '0755'

- name: copy files to host
  copy:
    src: "files/{{ item }}"
    dest: "{{ exporter_path }}/{{ item }}"
    mode: '0755'
  loop: "{{ exporter_files }}"

- name: extract filebeat
  unarchive:
    src: "{{ exporter_path }}/filebeat-8.13.4-linux-x86_64.tar.gz"
    dest: "{{ exporter_path }}"
    remote_src: yes
    extra_opts: "--strip-components=1"

- name: provide services
  template:
    src: "templates/{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    mode: '0644'
  loop: "{{ exporter_services }}"

- name: reload daemons
  systemd:
    daemon_reload: yes

- name: start exporters
  systemd:
    name: "{{ item }}"
    state: started
  ignore_errors: true
  loop: "{{ exporter_services }}"