---
- name: stop services
  systemd:
    name: "{{ item }}"
    state: stopped
  ignore_errors: true
  loop:
  - victoria-metrics
  - vminsert
  - vmselect
  - vmstorage
  - vmagent
  - grafana-server

- name: create group
  group:
    name: "{{victoria_user}}"
    state: present

- name: create user
  user:
    name: "{{victoria_user}}"
    state: present
    groups: "{{victoria_user}}"
    append: yes
    create_home: yes
    shell: /bin/bash

- name: create dirs
  file:
    path: "{{victoria_path}}/{{ item }}"
    state: directory
    owner: "{{victoria_user}}"
    group: "{{victoria_user}}"
    mode: '0755'
  loop:
  - vmstorage-data
  - vmagent-remotewrite-data

- name: copy files to server
  copy:
    src: "files/{{ item }}"
    dest: "{{victoria_path}}/{{ item }}"
  loop:
    - vminsert-prod
    - vmselect-prod
    - vmstorage-prod
    - vmagent-prod

### PROVIDE CONFIGS ###
- name: provide vminsert.service
  template:
    src: templates/vminsert.service.j2
    dest: /etc/systemd/system/vminsert.service
    mode: '0644'

- name: provide vmselect.service
  template:
    src: templates/vmselect.service.j2
    dest: /etc/systemd/system/vmselect.service
    mode: '0644'

- name: provide vmstorage.service
  template:
    src: templates/vmstorage.service.j2
    dest: /etc/systemd/system/vmstorage.service
    mode: '0644'

- name: reload daemons
  systemd:
    daemon_reload: yes

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
  ignore_errors: true
  loop:
  - vminsert
  - vmselect
  - vmstorage

# - name: start master services
#   systemd:
#     name: "{{ item }}"
#     state: started
#   ignore_errors: true
#   loop:
#   - vmagent
#   - grafana-server