---
- set_fact: master=False
  when: master is not defined

- name: stop services
  systemd:
    name: "{{ item }}"
    state: stopped
  ignore_errors: true
  loop:
  - victoria-metrics
  - vminsert
  - vmselect
  - vmstorage
  - vmagent
  - grafana-server

- name: create group
  group:
    name: "{{victoria_user}}"
    state: present

- name: create user
  user:
    name: "{{victoria_user}}"
    state: present
    groups: "{{victoria_user}}"
    append: yes
    create_home: yes
    shell: /bin/bash

- name: create dirs
  file:
    path: "{{victoria_path}}/{{ item }}"
    state: directory
    owner: "{{victoria_user}}"
    group: "{{victoria_user}}"
    mode: '0755'
  loop:
  - vmstorage-data
  - vmagent-remotewrite-data

- name: copy files to server
  copy:
    src: "files/{{ item }}"
    dest: "{{victoria_path}}/{{ item }}"
    mode: '0755'
  loop:
    - vminsert-prod
    - vmselect-prod
    - vmstorage-prod
    - vmagent-prod
    - vmauth-prod
    - node_exporter
    - system.json

- name: install grafana on master
  include_role:
    name: grafana
  when: master|bool

- name: configurate grafana
  include_role:
    name: grafana-configurate
  when: master|bool

- name: provide hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    mode: '0644'

- name: provide vminsert.service
  template:
    src: templates/vminsert.service.j2
    dest: /etc/systemd/system/vminsert.service
    mode: '0644'

- name: provide vmselect.service
  template:
    src: templates/vmselect.service.j2
    dest: /etc/systemd/system/vmselect.service
    mode: '0644'

- name: provide vmstorage.service
  template:
    src: templates/vmstorage.service.j2
    dest: /etc/systemd/system/vmstorage.service
    mode: '0644'

- name: provide vmagent.service
  template:
    src: templates/vmagent.service.j2
    dest: /etc/systemd/system/vmagent.service
    mode: '0644'

- name: provide vmauth.service
  template:
    src: templates/vmauth.service.j2
    dest: /etc/systemd/system/vmauth.service
    mode: '0644'

- name: provide node-exporter.service
  template:
    src: templates/node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: '0644'

- name: provide vmagent config
  template:
    src: templates/vmagent.yaml.j2
    dest: "{{victoria_path}}/vmagent.yaml"
    mode: '0644'

- name: provide vmauth config
  template:
    src: templates/vmauth.yaml.j2
    dest: "{{victoria_path}}/vmauth.yaml"
    mode: '0644'

- name: reload daemons
  systemd:
    daemon_reload: yes

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
  loop:
  - vminsert
  - vmselect
  - vmstorage
  - vmagent
  - vmauth
  - node-exporter

- name: start grafana server
  systemd:
    name: grafana-server
    state: started
  when: master|bool