---

### STOP SERVICES ###
- name: stop vminsert service
  systemd:
    name: vminsert
    state: stopped
  ignore_errors: true

- name: stop  vmselect service
  systemd:
    name: vmselect
    state: stopped
  ignore_errors: true

- name: stop vmstorage service
  systemd:
    name: vmstorage
    state: stopped
  ignore_errors: true 

- name: stop victoria-metrics service
  systemd:
    name: victoria-metrics
    state: stopped
  ignore_errors: true

### CREATE DIR'S ###
- name: create vmstorage dir
  file:
    path: "{{victoria_path}}/vmstorage-data"
    state: directory
    mode: '0755'

# - name: create data dir
#   file:
#     path: "{{victoria_path}}/data"
#     state: directory
#     mode: '0755'

- name: provide priveleges
  shell: "chown -R {{victoria_user}}:{{victoria_user}} {{victoria_path}}/vmstorage-data"

### INSTALL FILES ###
# - name: copy victoria-metrics
#   copy:
#     src: files/victoria-metrics-prod
#     dest: "{{victoria_path}}"
#     owner: root
#     group: root
#     mode: '0755'

- name: copy vminsert-prod
  copy:
    src: files/vminsert-prod
    dest: "{{victoria_path}}"
    owner: root
    group: root
    mode: '0755'

- name: copy vmselect-prod
  copy:
    src: files/vmselect-prod
    dest: "{{victoria_path}}"
    owner: root
    group: root
    mode: '0755'

- name: copy vmstorage-prod
  copy:
    src: files/vmstorage-prod
    dest: "{{victoria_path}}"
    owner: root
    group: root
    mode: '0755'

- name: copy vmagent-prod
  copy:
    src: files/vmagent-prod
    dest: "{{victoria_path}}"
    owner: root
    group: root
    mode: '0755'

### PROVIDE CONFIGS ###
# - name: provide victoria-metrics.service
#   template:
#     src: templates/victoria-metrics.service.j2
#     dest: /etc/systemd/system/victoria-metrics.service
#     mode: '0644'

# - name: provide master config
#   template:
#     src: templates/master-vmselect.yml.j2
#     dest: "{{victoria_path}}/vmselect.yml"
#     mode: '0644'
#   when: master|bool

# - name: provide slave config
#   template:
#     src: templates/slave-vm.select.yml.j2
#     dest: "{{victoria_path}}/vmselect.yml"
#     mode: '0644'
#   when: not master|bool

- name: provide vminsert.service
  template:
    src: templates/vminsert.service.j2
    dest: /etc/systemd/system/vminsert.service
    mode: '0644'

- name: provide vmselect.service
  template:
    src: templates/vmselect.service.j2
    dest: /etc/systemd/system/vmselect.service
    mode: '0644'

- name: provide vmstorage.service
  template:
    src: templates/vmstorage.service.j2
    dest: /etc/systemd/system/vmstorage.service
    mode: '0644'

### RELOAD DAEMONS ###
- name: reload daemons
  systemd:
    daemon_reload: yes

### START SERVICES ###
# - name: start victoria-metrics service
#   systemd:
#     name: victoria-metrics
#     state: started
#     enabled: yes

- name: start vminsert service
  systemd:
    name: vminsert
    state: started
    enabled: yes

- name: start vmselect service
  systemd:
    name: vmselect
    state: started
    enabled: yes

- name: start vmstorage service
  systemd:
    name: vmstorage
    state: started
    enabled: yes