---
### STOP SERVICES ###
- name: stop victoria-metrics
  systemd:
    name: victoria-metrics
    state: stopped
  ignore_errors: true

- name: stop vmagent
  systemd:
    name: vmagent
    state: stopped
  ignore_errors: true

- name: stop node-exporter
  systemd:
    name: node-exporter
    state: stopped
  ignore_errors: true
  
### CREATE USER ###
- name: create group
  group:
    name: "{{victoria_user}}"
    state: present

- name: create user
  user:
    name: "{{victoria_user}}"
    state: present
    groups: "{{victoria_user}}"
    append: yes
    create_home: yes
    shell: /bin/bash

### CREATE DIR'S ###
- name: create victoria dir
  file:
    path: "{{victoria_path}}/victoria-metrics-data"
    state: directory
    owner: "{{victoria_user}}"
    group: "{{victoria_user}}"
    mode: '0755'

- name: create vmagent dir
  file:
    path: "{{victoria_path}}/vmagent-remotewrite-data"
    state: directory
    owner: "{{victoria_user}}"
    group: "{{victoria_user}}"
    mode: '0755' 

### INSTALL FILES ###

- name: copy files to server
  copy:
    src: "files/{{ item }}"
    dest: "{{victoria_path}}/{{ item }}"
  loop:
    - victoria-metrics-prod
    - vmagent-prod
    - node_exporter
    - system.json

- name: provide victoria-metrics service
  template:
    src: templates/victoria-metrics.service.j2
    dest: /etc/systemd/system/victoria-metrics.service
    mode: '0644'

- name: provide vmagent service
  template:
    src: templates/vmagent.service.j2
    dest: /etc/systemd/system/vmagent.service
    mode: '0644'

- name: provide vmagent config
  template:
    src: templates/vmagent.yaml.j2
    dest: "{{victoria_path}}/vmagent.yaml"
    mode: '0644'

- name: provide node-exporter service
  template:
    src: templates/node-exporter.service.j2
    dest: /etc/systemd/system/node-exporter.service
    mode: '0644'

- name: provide datasource
  template:
    src: templates/vm.yml.j2
    dest: /etc/grafana/provisioning/datasources/vm.yml
    mode: '0644'

- name: provide dashboard
  template:
    src: templates/dashboard-system.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-system.yml
    mode: '0644'

### RELOAD DAEMONS ###
- name: reload daemons
  systemd:
    daemon_reload: yes

### START ###
- name: start victoria-metrics service
  systemd:
    name: victoria-metrics
    state: started
    enabled: yes

- name: start vmagent service
  systemd:
    name: vmagent
    state: started
    enabled: yes

- name: start node-exporter service
  systemd:
    name: node-exporter
    state: started
    enabled: yes

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    enabled: yes
