---
- name: copy files to host
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0755'
  loop:
    - elasticsearch-{{elk_version}}-x86_64.rpm # https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.4-x86_64.rpm
    - kibana-{{elk_version}}-x86_64.rpm # https://artifacts.elastic.co/downloads/kibana/kibana-8.13.4-x86_64.rpm

- name: install rpm's
  yum:
    name: "/tmp/{{ item }}"
    state: present
  loop:
  - elasticsearch-{{elk_version}}-x86_64.rpm
  - kibana-{{elk_version}}-x86_64.rpm

- name: copy config
  copy:
    src: "files/{{ item }}.yml"
    dest: "/etc/{{ item }}/{{ item }}.yml"
  loop:
  - elasticsearch
  - kibana

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - elasticsearch
  - kibana