---
- name: copy files to host
  copy:
    src: "files/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: '0755'
  loop:
    - elasticsearch-{{elk_version}}-x86_64.rpm # https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.13.4-x86_64.rpm
    - kibana-{{elk_version}}-x86_64.rpm # https://artifacts.elastic.co/downloads/kibana/kibana-8.13.4-x86_64.rpm

- name: install rpm's
  yum:
    name: "/tmp/{{ item }}"
    state: present
  loop:
  - elasticsearch-{{elk_version}}-x86_64.rpm
  - kibana-{{elk_version}}-x86_64.rpm

- name: copy elasticsearch config
  copy:
    src: files/elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml

- name: copy kibana config
  copy:
    src: files/kibana.yml
    dest: /etc/kibana/kibana.yml

- name: start services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  - kibana
  - elasticsearch