---
- set_fact: default_path={{victoria_path}}
  when: default_path is not defined

- name: copy files to server
  copy:
    src: "files/{{ item }}"
    dest: "{{default_path}}/{{ item }}"
  loop:
    - system.json
    - node_exporter_full.json

- name: provide datasource
  template:
    src: templates/vm.yml.j2
    dest: /etc/grafana/provisioning/datasources/vm.yml
    mode: '0644'

- name: provide dashboard
  template:
    src: templates/dashboard-system.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-system.yml
    mode: '0644'