---
- name: provide datasource
  template:
    src: templates/vm.yml.j2
    dest: /etc/grafana/provisioning/datasources/vm.yml
    mode: '0644'

- name: provide dashboard
  template:
    src: templates/dashboard-system.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-system.yml
    mode: '0644'