---
### CREATE DIR'S ###
- name: create dir
  file:
    path: "{{site_path}}/{{site_name}}"
    state: directory
    mode: '0755'

- name: copy site files to server
  copy:
    src: "files/{{ item }}"
    dest: "{{site_path}}/{{site_name}}/{{ item }}"
  loop:
    - index.html
    - style.css
    - d3js.js

### PROVIDE CONFIGS ###
- name: provide nginx config
  template:
    src: templates/config.conf.j2
    dest: "{{nginx_config_path}}/{{site_name}}.conf"
    mode: '0644'


### START SERVICES ###
- name: start service
  systemd:
    name: nginx
    state: restarted
    enabled: yes